### ISSUE TITLE
Memory leak on constant /predict requests

### ISSUE THREAD

**Issue by rguilmont** [jolibrain/deepdetect#1260]
#### Configuration

- Version of DeepDetect:
    - [X ] Locally compiled on:
        - [ ] Ubuntu 18.04 LTS
        - [ ] Other:
    - [ ] Docker CPU
    - [X ] Docker GPU

- Commit (shown by the server when starting):
    - `fa96e934cecedcb269eec772a223705aafa41914` ( no issue with this one )
    - `74cf54cce30b791def7712eabd0c93c31eebf91b` ( issue with this one )
    
#### Your question / the problem you're facing:

After we upgraded DeepDetect to version v0.15, we saw a constant increase in memory RAM ( **not** gpu ) consumption. 
Our services uses Cafe and Tensorrt.
Previous version `fa96e934cecedcb269eec772a223705aafa41914`  ( which is old, but was working well for us ) didn't had this issue. See the graph of memory available attached. We upgraded the service at about 10h35 :

![image](https://user-images.githubusercontent.com/20242692/114397923-7c277c80-9b9f-11eb-9d17-5453d66ecf2c.png)

When available memory goes to 0, DeepDetect is killed and restarted ( and thus free the memory ).

#### Error message (if any) / steps to reproduce the problem:

- Start DeepDetect from docker image : `jolibrain/deepdetect_gpu_tensorrt:v0.15.0`
- Load at least one model, for instance NSFW : 
```
curl -X PUT http://localhost:8080/services/nsfw -d '{
   "description": "nsfw classification service",
   "model": {
    "repository": "/tmp/models/nsfw",
    "create_repository": true,
    "init":"https://deepdetect.com/models/init/desktop/images/classification/nsfw.tar.gz"
   },
   "mllib": "tensorrt",
   "type": "supervised",
   "parameters": {
    "input": {
     "connector": "image"
    }
   }
  }
  '
```
- Run constant prediction queries, and notice how the ram goes high : 
```
while true; do
curl -X POST 'http://localhost:8080/predict' -d '{
              "service": "nsfw",
              "parameters": {
                      "output": {
        "best": 3
      },
      "mllib": {
        "gpu": true
      }
              },
              "data": [
                "https://picsum.photos/200/300"
              ]
            }'

done
```

**Comment by fantes** [comment]
Hi @rguilmont , thanks for the report. We started to investigate, but it seems that the leak does not happen when using valgrind (!), which makes it quite more difficult to investigate than expected. We will keep you informed as soon as we find somthing.

**Comment by rguilmont** [comment]
Oh, thanks for the update !

FYI i tried to reproduce locally with CPU, and i was not able to. I do see an increase in ram usage, but then it get stable. So i was able to replicate only with models loaded with tensorrt. If i can provide you more information, don't hesitate :)

**Comment by fantes** [comment]
yes, same behavior using tensorrt/GPU within valgrind :'(

**Comment by rguilmont** [comment]
I'll try to get more information about it, and maybe try to reproduce too with Valgrind if get the time to :)

I just hope this is not hardware related... That would makes thing even more complicated 😂 

FYI we've spotted the leak on g4dn.xlarge from Amazon with Tesla T4 gpu

**Comment by fantes** [comment]
Hi @rguilmont , we found the issue. Indeed @beniz has run in the same problem some time ago with tensorflow backend. We are currently trying to create a clean fix

**Comment by rguilmont** [comment]
Awesome news !! Out of curiosity, did you find it with Valgrind in the end ? :)

**Comment by beniz** [comment]
It's not a leak, you could actually run as is. It's the malloc library that fragments the memory due to underlying micro allocations, probably by trt.
Using tcmalloc instead of the standard malloc may do the trick.

**Comment by fantes** [comment]
should be better with https://github.com/jolibrain/deepdetect/pull/1262
