### ISSUE TITLE
Chain predictions swapped between images

### ISSUE THREAD

**Issue by YaYaB** [jolibrain/deepdetect#1348]
#### Configuration

- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [ ] Ubuntu 18.04 LTS
        - [ ] Other:
    - [X] Docker CPU
    - [X] Docker GPU
    - [ ] Amazon AMI
- Commit (shown by the server when starting):
 heads/v0.19.0:1673a99ecc922e01dd7cc8845098291ef46a8902

#### Your question / the problem you're facing:
I have observed recently some weird results for the chain request that can be summarized in two points:
- The predictions on bounding boxes after a crop are not associated to the correct images (when the data in the chain request contains at least 2 images)
- When an image does not have any prediction the uri appears in the predictions with an empty list as predictions. However when we chain with at least 2 images, the uri of the one who does not have any prediction does not appear.

We will go a bit deeper in the next part.

Please use the  `chain_issue.sh` attached (inside `chain_issue.zip`) to replicate all of this.
Simply fill the `BASE_PATH` and launch the script on a machine that has a gpu.

It will launch predictions for two images (one that contains a face and another that does not) for multiple cases:
- on cpu
- on gpu
- on gpu with tensorrt

You will find attached in the folder logs (inside `chain_issue.zip`) all the predictions results.
#### Error message (if any) / steps to reproduce the problem:
- Let us first observe the results based on the chain request for one example that contains a face.
The results are similar for cpu, gpu and gpu + tensorrt ()
`prediction_chain_deepdetect_cpu_v0.19.0_with_face.json`, `prediction_chain_deepdetect_gpu_tensorrt_v0.19.0_with_face.json`, `prediction_chain_deepdetect_gpu_v0.19.0_with_face.json`
```
{
    "status": {
        "code": 200,
        "msg": "OK"
    },
    "head": {
        "method": "/chain",
        "time": 6953.0
    },
    "body": {
        "predictions": [
            {
                "uri": "https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg",
                "classes": [
                    {
                        "age": {
                            "classes": [
                                {
                                    "prob": 0.05116057023406029,
                                    "cat": "48"
                                },
                                {
                                    "prob": 0.049001216888427737,
                                    "cat": "52"
                                },
                                {
                                    "prob": 0.04839149862527847,
                                    "cat": "51"
                                },
                                ....
                                {
                                    "prob": 0.000023848948330851273,
                                    "cat": "95"
                                },
                                {
                                    "prob": 0.00002303411383763887,
                                    "cat": "99"
                                },
                                {
                                    "prob": 0.00002025881076406222,
                                    "cat": "98"
                                },
                                {
                                    "last": true,
                                    "prob": 0.000016593863620073536,
                                    "cat": "97"
                                }
                            ]
                        },
                        "last": true,
                        "bbox": {
                            "ymax": 350.2694091796875,
                            "xmax": 745.9049682617188,
                            "ymin": 108.38542938232422,
                            "xmin": 528.0482788085938
                        },
                        "prob": 0.9999849796295166,
                        "cat": "1"
                    }
                ]
            }
        ]
    }
}
```

- Now let us do the same exercise with an image that does not have any face:
The results are similar for cpu, gpu and gpu + tensorrt ()
`prediction_chain_deepdetect_cpu_v0.19.0_no_face.json`, `prediction_chain_deepdetect_gpu_tensorrt_v0.19.0_no_face.json`, `prediction_chain_deepdetect_gpu_v0.19.0_no_face.json`
```
{
    "status": {
        "code": 200,
        "msg": "OK"
    },
    "head": {
        "method": "/chain",
        "time": 5834.0
    },
    "body": {
        "predictions": [
            {
                "classes": [],
                "uri": "https://picsum.photos/id/10/600/600"
            }
        ]
    }
}
```

- Now let us use the two images and observe what we get:
The results are similar for cpu, gpu and gpu + tensorrt ()
`prediction_chain_deepdetect_cpu_v0.19.0.json`, `prediction_chain_deepdetect_gpu_tensorrt_v0.19.0.json`, `prediction_chain_deepdetect_gpu_v0.19.0.json`
```
{
    "status": {
        "code": 200,
        "msg": "OK"
    },
    "head": {
        "method": "/chain",
        "time": 12899.0
    },
    "body": {
        "predictions": [
            {
                "uri": "https://picsum.photos/id/10/600/600",
                "classes": [
                    {
                        "age": {
                            "classes": [
                                {
                                    "prob": 0.05116057023406029,
                                    "cat": "48"
                                },
                                {
                                    "prob": 0.049001216888427737,
                                    "cat": "52"
                                },
                                ....
                                {
                                    "last": true,
                                    "prob": 0.000016593863620073536,
                                    "cat": "97"
                                }
                            ]
                        },
                        "last": true,
                        "bbox": {
                            "ymax": 350.2694091796875,
                            "xmax": 745.9049682617188,
                            "ymin": 108.38542938232422,
                            "xmin": 528.0482788085938
                        },
                        "prob": 0.9999849796295166,
                        "cat": "1"
                    }
                ]
            }
        ]
    }
}
```

As we can see we get the results for the image `https://picsum.photos/id/10/600/600` however we saw before that this image does not have any face. Moreover those predictions are exactly the one as we observed before for `https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg`.

We can then make the hypothesis that **the predictions are swapped between input images...**
An important note is that **we have no predictions** `https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg` but the previous request showed that when we do not have any predictions that matched we have results with empty lists, but no here. That is the second issue we observed.

To try to understand what happens we decided to verify how the  **mapping between inputs and  predictions** is made.
We found out in here https://github.com/jolibrain/deepdetect/blob/5efbf283f8056fef09512db7a11277b0f15ecd2d/src/chain_actions.cc#L39-L41 that we get the images and predictions separately

Then iterations are made over predictions (https://github.com/jolibrain/deepdetect/blob/5efbf283f8056fef09512db7a11277b0f15ecd2d/src/chain_actions.cc#L66-L70) and we get the image based on the index of this list. However nothing seem to indicate that the images' order as input is the same as the predictions'.

We may add to the hypothesis that it may come from **how the images and predictions are matched during a chain a request**.

Now we can easily verify this by doing a classical prediction and observe if the predictions returned are in the same order as the images in put. For every request the data is the following ["https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg", "https://picsum.photos/id/10/600/600"]

- First we do that for the face detection model
The results are the same for cpu, gpu and gpu + tensorrt
`prediction_deepdetect_cpu_v0.19.0_face_det.json`, `prediction_deepdetect_gpu_tensorrt_v0.19.0_face_det.json`, `service_creation_deepdetect_gpu_tensorrt_v0.19.0_face_det.json`
```
{
  "status": {
    "code": 200,
    "msg": "OK"
  },
  "head": {
    "method": "/predict",
    "service": "face_detection",
    "time": 12997
  },
  "body": {
    "predictions": [
      {
        "classes": [],
        "uri": "https://picsum.photos/id/10/600/600"
      },
      {
        "classes": [
          {
            "last": true,
            "bbox": {
              "ymax": 350.2694091796875,
              "xmax": 745.9049682617188,
              "ymin": 108.38542938232422,
              "xmin": 528.0482788085938
            },
            "prob": 0.9999849796295166,
            "cat": "1"
          }
        ],
        "uri": "https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg"
      }
    ]
  }
}
```
Here we observe that the first image `https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg` is now second in the results.

- Now for the age model
The results are the same for cpu, gpu and gpu + tensorrt
`prediction_deepdetect_cpu_v0.19.0_age.json`, `prediction_deepdetect_gpu_tensorrt_v0.19.0_age.json`, `service_creation_deepdetect_gpu_tensorrt_v0.19.0_age.json`
```
{
  "status": {
    "code": 200,
    "msg": "OK"
  },
  "head": {
    "method": "/predict",
    "service": "age",
    "time": 2278
  },
  "body": {
    "predictions": [
      {
        "classes": [
          {
            "prob": 0.02728383056819439,
            "cat": "55"
          },
          {
            "prob": 0.026149429380893707,
            "cat": "50"
          },
          ....
          {
            "last": true,
            "prob": 0.0050649153999984264,
            "cat": "64"
          }
        ],
        "uri": "https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg"
      }
    ]
  }
}
```

Here again we observe that the first image `https://icour.fr/ELeveSeconde/ajout/yann_lecum_vidal/images/yann_LeCun.jpg` is now second in the results.

That seems to be compliant with our latest hypothesis, and in the end we observed:
- Predictions after a crop can be associated to a wrong images (may be due to how images and crops are matched in the chain process)
- When we do not have any results we should have empty list (it is the case when we have one image in the request but no the case when we have several images in the request)

Note that those issues appear in cpu, gpu and gpu + tensorrt (batch size does not affect this).

[chain_issue.zip](https://github.com/jolibrain/deepdetect/files/7258934/chain_issue.zip)

**Comment by Bycob** [comment]
Hi @YaYaB, I could reproduce the bug on v0.19.0, however we refactored the chains recently and it looks like the bug is solved if you use the latest master.
You can try on latest dockers (tag ci-master) to check that the bug is gone.

**Comment by YaYaB** [comment]
@Bycob That's great news! I tried with the latest version `ci-master` and it seems to work.
Cheers to the team!
