### ISSUE TITLE
dd_client  not find in this path anyone help 

### ISSUE THREAD

**Issue by irfanahme** [jolibrain/deepdetect#1405]
i am not find dd_client file anyone help finding files

**Comment by beniz** [comment]
@irfanahme have you looked at the documentation here: https://github.com/jolibrain/deepdetect/tree/master/clients/python

Alternatively, the file is here: https://github.com/jolibrain/deepdetect/blob/master/clients/python/dd_client/__init__.py
You can rename it as `dd_client.py`

**Comment by irfanahme** [comment]
@beniz thanks for helping
