### ISSUE TITLE
How do I do a face recognition using this?

### ISSUE THREAD

**Issue by xcellenceit** [jolibrain/deepdetect#1406]
While I know how to do face detection, how can I do face recognition / matching using this?

**Comment by beniz** [comment]
You could use the similarity search capability, see https://www.deepdetect.com/applications/img_simsearch/ but most likely you may want to use a system dedicated to face recognition, which DeepDetect is not.

**Comment by xcellenceit** [comment]
Ok. Can you please let me know what would you recommend based on your experience.
