### ISSUE TITLE
"best: -1" in predict behaves differently in torch models

### ISSUE THREAD

**Issue by cchadowitz-pf** [jolibrain/deepdetect#1456]
It seems that when using the output param `"best": -1` in a `predict` call to a libtorch model, the behavior is different, at least compared to caffe (and I suspect most other backends) in DD. 

For caffe at least, using `"best": -1` returns all predictions. For torch models, it returns none. I believe this is because `best` is stored in `best_count` [here](https://github.com/jolibrain/deepdetect/blob/master/src/backends/torch/torchlib.cc#L1387)  so long as any value for `best` is provided. Then [here](https://github.com/jolibrain/deepdetect/blob/master/src/backends/torch/torchlib.cc#L1707) the value is used as is without any validation, and if it is `-1`, then it will obviously examine and return zero predictions.

In contrast, the SupervisedOutputConnecter [here](https://github.com/jolibrain/deepdetect/blob/master/src/supervisedoutputconnector.h#L251) checks for the value of `-1` and if true, uses `nclasses` instead.

An example `predict` call would be something like:

```
curl -X POST "http://localhost:8080/predict" -d '{
  "service":"myservice",
  "parameters":{
    "output":{"best":-1}
  },
  "data":["cat.jpg"]
}'
```

**Comment by fantes** [comment]
thanks a lot! I think we never use best = -1 here...

**Comment by cchadowitz-pf** [comment]
Hah we have for a while so this caught us by surprise!
