### ISSUE TITLE
Support for mxnet

### ISSUE THREAD

**Issue by loweew** [jolibrain/deepdetect#236]
Would love to see mxnet support for recognition and, eventually, detection.

**Comment by beniz** [comment]
This is something that we are opened to support. There's an ongoing conversation here: https://github.com/dmlc/mxnet/issues/1873
I am waiting a bit to see how this conversation evolves or resolves.

Overall it should not be too difficult to support mxnet in prediction. One reason is that DD already has support for xgboost that may share some similarities codewise. Another is that mxnet appears pretty clean and is written in C++.

**Comment by beniz** [comment]
Hi, mxnet support is not on the roadmap. Caffe and Caffe2 are the main DL backends. One way to get mxnet models in would be to convert them, maybe with onnx. 

That being said, external contributions can be agreed upon, you may want to look at the recent dlib integration.
