### ISSUE TITLE
Training log dump after training

### ISSUE THREAD

**Issue by EBazarov** [jolibrain/deepdetect#354]
There is possibility to have training log by using parameter `parameters.output.measure_hist` in call to DeepDetect, described [here](https://deepdetect.com/api/#get-information-on-a-training-job).
But if after fitting model we will remove service from a server, information about training will be lost, because it's not stored anywhere. That will be useful to have log file inside folder with model. I can do it with a script, but maybe it will be interesting feature for DeepDetect.

**Comment by beniz** [comment]
See #480.
