### ISSUE TITLE
No patch step for "caffe_dd"

### ISSUE THREAD

**Issue by nikhil791** [jolibrain/deepdetect#371]
Hi Beniz,

During installation i am getting some errors. I am on centos 6.8 . Below is the output of cmake
cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
-- filesystem
-- thread
-- system
-- iostreams
-- OpenCV 2 (2.4.11) found (/usr/local/share/OpenCV)
-- Configuring customized caffe
-- Build Tests : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cascade/nikhil/DD/deepdetect

when i ran the command "make" i am getting the following error:
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- downloading... done
-- verifying file...
file='/home/cascade/nikhil/DD/deepdetect/caffe_dd/src/master.tar.gz'
-- verifying file... warning: did not verify file - no URL_HASH specified?
-- extracting...
src='/home/cascade/nikhil/DD/deepdetect/caffe_dd/src/master.tar.gz'
dst='/home/cascade/nikhil/DD/deepdetect/caffe_dd/src/caffe_dd'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 11%] No patch step for 'caffe_dd'
[ 15%] No update step for 'caffe_dd'
[ 19%] Performing configure step for 'caffe_dd'
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make[3]: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1
make[2]: *** [caffe_dd/src/caffe_dd-stamp/caffe_dd-configure] Error 2
make[1]: *** [CMakeFiles/caffe_dd.dir/all] Error 2
make: *** [all] Error 2

can you please help me out..??

**Comment by beniz** [comment]
Hi,  centos is not among pur supported platforms,  see the readme and documentation. In the present case your compiler is too old.  Try gcc4.x or gcc5. Or use one of the docker images.

**Comment by nikhil791** [comment]
gcc version is 4.4.7.. Will it work on this version or do I need to install gcc version 4.8..?

**Comment by nikhil791** [comment]
Hi Beniz, 

I have gcc version= 4.8.2. 
Still I am getting the error: 
cc1plus: error: unrecognized command line option "-std=c++11"

It would be great if you can help me..?

**Comment by fantes** [comment]
-std=c++11 is supported since gcc 4.7 https://gcc.gnu.org/gcc-4.7/cxx0x_status.html 
- you should check that the gcc you are running is the new one :  gcc --version 
- but from https://gcc.gnu.org/projects/cxx-status.html#cxx11   you can see that "GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard, previously known as C++0x", so use with caution.
