### ISSUE TITLE
What data was used to train the Russian-language sentiment analysis model? 

### ISSUE THREAD

**Issue by zhanser1k** [jolibrain/deepdetect#410]
Hi @beniz , thanks for the great work! I have a question: If I want to overtrain the model on my texts, what do I need to do?

**Comment by beniz** [comment]
Hi, not sure I understand the 'overtrain' question. Data for the Russian language sentiment model are from an old dataset of mine (around 2013) gathered from Twitter, using emojis/smileys to estimate the sentiment. Don't use this in production, this is a demo dataset/model at best.

**Comment by zhanser1k** [comment]
@beniz sorry for my bad english, i just want to retrain the model with my dataset, i have a good dataset that contains a lot of tweets. How can i do this?

**Comment by beniz** [comment]
You may want to look at https://deepdetect.com/overview/examples/#character-based-deep-convolutional-neural-networks:9ecc00cd7c4c5bc9e8febc4fe00186bf and https://deepdetect.com/overview/examples/#finetuning-googlenet:9ecc00cd7c4c5bc9e8febc4fe00186bf and the documentation on general.
