### ISSUE TITLE
Check failed (custom): (axis_index) < (num_axes())

### ISSUE THREAD

**Issue by cchadowitz-pf** [jolibrain/deepdetect#417]
#### Configuration
- Version of DeepDetect: `a12905d` and `91ec05ef09f2d465d43faf4a31b176c0a627462e`
    - [x] Locally compiled on:
        - [x] Ubuntu 16.04 LTS
    - [x] Docker
- Commit (shown by the server when starting):
`a12905d` and `91ec05ef09f2d465d43faf4a31b176c0a627462e`

#### Your question / the problem you're facing:
For one particular Caffe model I'm using, attempting a `PUT` to create a service for the model results in a 500 error.

#### Error message (if any) / steps to reproduce the problem:
- [ ] list of API calls:
- `curl http://localhost:8080/info` - to verify the server is indeed running
- `curl -X PUT "http://localhost:8080/services/nsfw" -d @/opt/models/nsfw/init.json` - to create the service for the particular model (`init.json` is here: https://gist.github.com/cchadowitz-pf/4907f0daf6936e21e840195390078397)

- [ ] Server log output:
Full server log output in this gist: https://gist.github.com/cchadowitz-pf/c66cc5752fc32c1d4e928aec20a67ab8

Relevant part:
```
[2018-05-21 20:11:25.212] [nsfw] [error] Error creating network
[2018-05-21 20:11:25.212] [nsfw] [error] service creation call failed
[2018-05-21 20:11:25.212] [api] [error] 127.0.0.1 "PUT /services/nsfw" 500 5875
```

And the message returned was:
```
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"/opt/deepdetect/build/caffe_dd/src/caffe_dd/include/caffe/blob.hpp:124 / Check failed (custom): (axis_index) < (num_axes())"}}
```

Associated `deploy.prototxt` and `corresp.txt` are available here: https://gist.github.com/cchadowitz-pf/2a25e666ad0d9ec6307630d734c339b8

Caffe model weights are here: https://github.com/yahoo/open_nsfw/blob/master/nsfw_model/resnet_50_1by2_nsfw.caffemodel

**Comment by cchadowitz-pf** [comment]
This fails with both GPU support and without, so GPU is not a factor here.

**Comment by cchadowitz-pf** [comment]
This issue was not present in `971eadb202cd7f892dad6a42b2993d6a6ce54128`, trying to narrow it down as many commits happened between then and now :)

**Comment by cchadowitz-pf** [comment]
Update:

It seems something has changed either in upstream Caffe or in a change in the https://github.com/jolibrain/caffe/ fork that causes this issue for this particular model only if the second to last layer (`fc_nsfw`) contains a `weight_filler` and `bias_filler` section like so:
```
layer {
   name: "fc_nsfw"
   type: "InnerProduct"
   bottom: "pool"
   top: "fc_nsfw"
   param {
       lr_mult: 5
       decay_mult: 1
   }
   param {
       lr_mult: 10
       decay_mult: 0
   }
   inner_product_param{
       num_output: 2
       weight_filler {
         type: "xavier"
         std: 0.01
       }
       bias_filler {
          type: "xavier"
          value: 0
       }
   }
}
```

However, the `weight_filler` and `bias_filler` sections are only used during training, not inference (although they clearly are still parsed/loaded for inference as well). When this `fc_nsfw` layer is modified to the following, this issue is no longer present:
```
layer {
   name: "fc_nsfw"
   type: "InnerProduct"
   bottom: "pool"
   top: "fc_nsfw"
   inner_product_param{
	   num_output: 2
   }
}
```

This still leaves the question of what is causing this error to come up now (as it didn't previously), because if a similar model was used during training it would still need the `weight_filler` and `bias_filler` sections.

**Comment by cchadowitz-pf** [comment]
Narrowing this down further, it seems the culprit is the `bias_filler` when the type is set to `xaviar`. I can also trigger this issue in other Caffe models by adding a block like the following to the last `InnerProduct` (i.e. fully connected) layer in the `inner_product_param` section:
```
bias_filler {
        type: "xavier"
        value: 0
     }
```

**Comment by beniz** [comment]
It should be enough to check whether https://github.com/BVLC/caffe/pull/6278 has been merged into our custom caffe.

**Comment by beniz** [comment]
Thanks for your help, we were missing the Caffe fix from https://github.com/BVLC/caffe/commit/69da2cf934b1ff611ad6c5a2e1523e22f036d2ad 
It's been merged and we'll issue new docker builds.

Please reopen if this does not fix your issue.
