### ISSUE TITLE
running prediction on gpu 

### ISSUE THREAD

**Issue by BabakPA** [jolibrain/deepdetect#441]
- [x] [all prerequisite tools](http://www.deepdetect.com/overview/installing/ "DeepDetect installation page") and [dependencies](https://github.com/beniz/deepdetect#user-content-dependencies "DeepDetect README page on Github") are installed.

#### Configuration
- Version of DeepDetect: 
    - [ ] Docker

#### Your question / the problem you're facing:

Hi , I want to predict with some pretrained models (for example with vgg16 or resnet50 )on GPU .
I have put the corresponding .caffemodel , deploy.prototxt and corresp.txt in the repository folder. 
the problem is i cant run prediction on GPU but on CPU it runs succeessfully. 

and also there is another thing that prediction with ggnet pretrained model runs perfectly on gpu . 
the question is why other models cant run on gpu ? why just ggnet . 
do i need to add other files in addition to the .caffemodel , deploy.prototxt and corresp.txt in the repository folder  ? 
also i have noticed  in the default ggnet folder there are  2 other files (googlenet.prototxt and googlenet_solver.prototxt ) in addition to those three files . when i remove these 2 files from the ggnet repository folder i cant run prediction on gpu . but based on the document these 2 files only related to training tasks and wont be used in the prediction tasks . so why when i remove them , the prediction task failes on gpu .

Error :
 {"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/syncedmem.cpp:56 / Check failed (custom): (error) == (cudaSuccess)"}}

**Comment by AminUCo** [comment]
Hi, I have the same problem.
i get same error sometimes:
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/util/im2col.cu:61 / Check failed (custom): (error) == (cudaSuccess)"}}
I have given two exact the same requests, but i have got two completely different answers?
![issue](https://user-images.githubusercontent.com/38522922/41509423-9b81e7ae-7268-11e8-8aa3-b284676cf4c4.png)

**Comment by BabakPA** [comment]
I'm running prediction on Geforce gt 930m not 1080 . 930m architecture  is Maxwell . so my problem is not related to the gpu architecture .

**Comment by beniz** [comment]
I believe it's coming from the `nvidia/cuda` docker that has moved to cuda-9.2 and maybe this does not work with some old architectures we are building for by default. 

@AminUCo can youl try pulling out docker build `beniz/deepdetect_gpu_pascal` ? It is a dedicated Pascal (cuda compute `61`) build and works for me.

**Comment by BabakPA** [comment]
i dont think thats the case . because when i want to predict on gpu with default ggnet folder repo, it runs successfully on gpu but when i remove these 2 files (googlenet.prototxt and googlenet_solver.prototxt ) from the folder it failes . why is this happening these 2 files related to training not prediction . 
 
if it was due to nvidia-docker it shouldnt run on gpu at all . it seems its a bug . 
so are these 3 files : (.caffemodel - deploy.prototxt -corresp .txt ) enough to run prediction on gpu ? 
am i right ?

**Comment by beniz** [comment]
@AminUCo let's bounce this again to its own issue this time, #442.

**Comment by beniz** [comment]
> why other models cant run on gpu

Alll models run on GPUs.

> do i need to add other files in addition to the .caffemodel , deploy.prototxt and corresp.txt in the repository folder ?

You don't and these three files are enough to run googlenet. 

> {"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/syncedmem.cpp:56 / Check failed (custom): (error) == (cudaSuccess)"}}

You do not have enough memory to run the models you are on. The 930m has 2GB of memory, this may not be enough for some models, even with batch size set to 1.

**Comment by BabakPA** [comment]
if it was due to memory error why it runs on gpu successfully with default ggnet folder and it fails when i remove those 2 files . 
and i have tested this matter on 1080ti  the same thing happens. 
and also prediction with other models like vgg , resnet wont run on gpu too.

**Comment by beniz** [comment]
You can post your exact API calls and server output. I've tested without the two files, just in case, and it works fine.

**Comment by AminUCo** [comment]
I'm running prediction on geforce gt 940mx (2G memory) . I have given two exact the same requests(with one image), but i have got two completely different answers!!!!!!!!!!!!Once the output is correct and once the error output
In addition, I run prediction with batch_size =32 and not problam with error " not have enough memory" !!!

**Comment by BabakPA** [comment]
Thank you very much @beniz , with the new deepdetect-gpu-docker-image the problems on 1080ti has gone .
