### ISSUE TITLE
Caffe2 build breaks XGBoost build due to log header conflict

### ISSUE THREAD

**Issue by beniz** [jolibrain/deepdetect#443]
Caffe2 build breaks the XGBoost build. Should be reproduced with:
```
cmake .. -DUSE_CAFFE2=ON -DUSE_XGBOOST=ON
```

Error:
```
build/xgboost/src/xgboost/rabit/include/dmlc/logging.h:149:23: error: ‘LOG_VLogLevels’ was not declared in this scope
```

Internal Jolibrain build link: http://10.10.77.61:10080/blue/organizations/jenkins/deepdetect/detail/test_jenkins_jb/10/pipeline

**Comment by chichaj** [comment]
#444 Should fix this error
