### ISSUE TITLE
Adding other libraries to deepdetect API

### ISSUE THREAD

**Issue by BabakPA** [jolibrain/deepdetect#448]
- [ ] [all prerequisite tools](http://www.deepdetect.com/overview/installing/ "DeepDetect installation page") and [dependencies](https://github.com/beniz/deepdetect#user-content-dependencies "DeepDetect README page on Github") are installed.

#### Configuration
- Version of DeepDetect:   
    - [ ] Docker
 
#### Your question / the problem you're facing:
Hi
@beniz I have written some libraries with c++ and python . I want to add them to deepdetect api . what should i do ? is there any tutorial or document for this purpose ? 
thanks

**Comment by beniz** [comment]
Not really, and it may be more or less easy depending on the library. You can look at simple examples with `tsnelib`, `xgblib` and `tflib`.
