### ISSUE TITLE
train on  a distributed dataset with deepdetect-caffe 

### ISSUE THREAD

**Issue by BabakPA** [jolibrain/deepdetect#450]
- Version of DeepDetect:    
    - [ ] Docker
   
#### Your question / the problem you're facing:
Hi
I want to train a network with deepdetect-caffe. my training dataset is distributed in different folders and  sub folders . In caffe we have a txt file which contains  the locations of images and their corresponding labels . but in deepdetect what should i do ?

**Comment by beniz** [comment]
Hi, issues are for bugs or feature requests, please use the gitter chat https://gitter.im/beniz/deepdetect for questions, thanks.
