### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by YaYaB** [jolibrain/deepdetect#484]
The certificate used on https://deepdetect.com is expired since August the 7th.

```
deepdetect.com utilise un certificat de sécurité invalide. Le certificat a expiré le 7 août 2018 à 11:33:13 UTC+2. La date courante est 8 août 2018 à 09:29. 
Code d’erreur : SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by beniz** [comment]
Nginx was on vacations and did not reload automatically after renewal :) This has been fixed the day after. Thanks for reporting !
