### ISSUE TITLE
Model repository does not read correctly on XFS filesystem

### ISSUE THREAD

**Issue by beniz** [jolibrain/deepdetect#50]
As explained in http://nerdfortress.com/2008/09/19/linux-xfs-does-not-support-direntd_type/ XFS does not support direntd and everything appears as a regular file. 
This one post http://stackoverflow.com/a/29094555 also reports possible workaround by testing for DT_UNKNOWN and using `lstat` on every file.

**Comment by cchadowitz-pf** [comment]
The first link seems to be broken - here's a cached version: https://web.archive.org/web/20160315093719/http://nerdfortress.com/2008/09/19/linux-xfs-does-not-support-direntd_type/
