### ISSUE TITLE
Service Bad Request Error: error reading or listing Caffe models

### ISSUE THREAD

**Issue by Vulcainreo** [jolibrain/deepdetect#508]
#### Configuration
- Version of DeepDetect:
    - [x] Docker
- Commit (shown by the server when starting):633dbcca38e047154b058a8063fd44a930e85d4c

#### Problem:
I would like to start the text classification example. I started the docker image the dede server is well up : 
```
curl http://localhost:8080/info 
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"633dbcca38e047154b058a8063fd44a930e85d4c","services":[{"mltype":"classification","name":"imageserv","description":"image classification service","mllib":"caffe","predict":true}]}}
```
But, with this fresh install : when I would like to create the service, I receive an error
````

curl -X PUT "http://localhost:8080/services/n20" -d '{
       "mllib":"caffe",
       "description":"newsgroup classification service",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"txt"
         },
         "mllib":{
           "template":"mlp",
           "nclasses":20,
           "layers":[200,200],
           "activation":"relu"
         }
       },
       "model":{
         "templates":"../templates/caffe/",
         "repository":"models/n20"
       }
     }'

{"status":{"code":400,"msg":"BadRequest","dd_code":1006,"dd_msg":"Service Bad Request Error: error reading or listing Caffe models in repository models/n20"}}
````

Did I miss something during the setup ?
Thank you in advance for your help.

Best regards,
Vulcainreo

**Comment by beniz** [comment]
Hi you need to have the model directory readable from within the docker image. Look at the docker readme how to share a volume between the docker and the host, and look at general docker doc as well. Using absolute paths is also recommended.
