### ISSUE TITLE
Not Able to make outbound calls to localhost from docker container

### ISSUE THREAD

**Issue by ankitiitb1069** [jolibrain/deepdetect#532]
#### Configuration
- Version of DeepDetect:
    - Docker
- Commit (shown by the server when starting): c3bbec74d72b12a8a31aaf044df5f132d80ce5e7251b7dee738a150ac64e2d02

#### Error message (if any) / steps to reproduce the problem: 
- list of API calls: http://localhost:8080/predict

- Server log output: [2019-01-22 07:48:03.878] [api] [error] Failed to connect to 127.0.0.1 port 9200: Connection refused

**Comment by beniz** [comment]
Hi, you may not be able to reach elastic from a DD docker, unless you configure your network appropriately. My understanding is that the error comes from trying to lookup elastic on port 9200 inside the docker instead of on the host machine.

**Comment by ankitiitb1069** [comment]
yes, but most of the places I found, it to be the case, the solution is different for different platforms like MacOS or Linux, so I would really appreciate if something on lines of  [this](https://dev.to/bufferings/access-host-from-a-docker-container-4099) is added to dockerfile so that it becomes easier to use across operating systems

**Comment by beniz** [comment]
I believe the good practice is not communicating with the host but with other containers as well. This means you should get your elastic into a docker and configure the network in between containers via docker-compose. This is what we are doing for our own purposes.
