### ISSUE TITLE
Detectron mask rcnn runtime error

### ISSUE THREAD

**Issue by intgogo** [jolibrain/deepdetect#547]
It's ok to run mask-rcnn service without 'scaled', 'scale_min', 'scale_max' parameters.
After doing more tests,I find out that input parameters 'width' and 'height' must be 224*n.（eg.448,896）
How can I fix this bug?

**Error results:**
[error] Error while running the network: [enforce fail at utility_ops.h:276] . Check failed: output->dims() == Input(i).dims().Description: Input #1, input dimension:1 256 64 64 should match output dimension: 1 256 63 63Error from operator: 
input: "fpn_inner_res4_22_sum_lateral" input: "fpn_inner_res4_22_sum_topdown" output: "fpn_inner_res4_22_sum" name: "" type: "Sum" device_option { device_type: 1 cuda_gpu_id: 0 } engine: ""

**Create service:**
curl -X PUT "http://localhost:8182/services/mrcnn50" -d '{
      "description": "detectron",
      "type": "supervised",
      "mllib": "caffe2",
      "parameters": {
        "input": {
          "connector": "image",
          "scale_min":800,
          "scale_max":1333,
          "mean": [102.9801, 115.9465, 122.7717]
        },
        "mllib": { "gpu": true }
      },
      "model": {
        "repository": "/root/lilw/deepdetect/build/test/mrcnn/model/",
        "extensions": [{"type" : "mask"}]
      }
    }'

**Predict:**
curl -X POST "http://localhost:8182/predict" -d '{
  "service": "mrcnn50",
  "parameters": {
    "output": {
      "mask": true,
      "best": 1,
      "confidence_threshold": 0.7
    }
  },
  "data": [ "../../test/all.jpg" ]
}'

**Comment by intgogo** [comment]
@chichaj @beniz 
Same error when I try caffe2 xception classifier.

{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"[enforce fail at utility_ops.h:276] . Check failed: output->dims() == Input(i).dims().Description: Input #1, input dimension:1 256 27 27 should match output dimension: 1 256 28 28Error from operator: \ninput: \"xception2_match_conv\" input: \"xception2_pool\" output: \"xception2_elewise\" type: \"Sum\" device_option { device_type: 1 cuda_gpu_id: 0 }"}}

**Create:**
curl -X PUT "http://localhost:8182/services/xception_caffe2" -d '{
       "mllib":"caffe2",
       "description":"test",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"image",
            "width":224, 
            "height":224,
            "db":true
         },
         "mllib":{
           "nclasses":1000,
           "gpu":true,
           "gpuid":[0,1,2,3],
           "template":"xception"
         }
       },
       "model":{
         "templates":"/root/lilw/deepdetect/templates/caffe2/",
         "repository":"/root/lilw/deepdetect/build/test/xception/"
       }
     }'

**Predict:**
curl -X POST "http://localhost:8182/predict" -d '{ "service":"xception_caffe2", "parameters":{ "input":{ "width":224, "height":224 }, "output":{ "best":3 } }, "data":["../../test/ambulance.jpg"]}'

**Comment by intgogo** [comment]
By the way,where can I download the pretrained weights for caffe2? eg. xception

**Comment by beniz** [comment]
> After doing more tests,I find out that input parameters 'width' and 'height' must be 224*n.（eg.448,896）
How can I fix this bug?

I'm pretty sure this is not a bug but that input tensors need to follow some input ratio with detectron, but @chichaj will give a final verdict on this.

**Comment by chichaj** [comment]
> > After doing more tests,I find out that input parameters 'width' and 'height' must be 224*n.（eg.448,896）
> > How can I fix this bug?
> 
> I'm pretty sure this is not a bug but that input tensors need to follow some input ratio with detectron, but @chichaj will give a final verdict on this.

It's indeed not a bug but is inherent to the model architecture. This happens because of consecutive 2x down-samplings made by certain layers. After a few of them are done, an odd number is forced to be divided by 2 and end up being (wrongly) rounded. It results in a tensor with the wrong shape (here 63 instead of 64).

Some architectures simply require inputs to be shaped as multiples of a certain value (usually 16, 64 or 224).

> By the way,where can I download the pretrained weights for caffe2? eg. xception

Most of caffe2's templates were created using those models: https://github.com/rai-project/caffe2/tree/master/builtin_models

Link to the original ```predict_net.pb``` and ```init_net.pb``` (the weights) are available in the corresponding ```.yml``` files.

Xception was one of them, but was removed in December ([the commit here](https://github.com/rai-project/caffe2/commit/33c978662f07143153a5bf0b764b2dbe5f6c51c3#diff-7f307059e16818f96885a5c799086f08))

It appears that the original weights are no longer hosted ...

**Comment by beniz** [comment]
> Xception was one of them, but was removed in December

There are weights for Caffe, though we haven't tested them, https://github.com/yihui-he/Xception-caffe

However, there are many other relevant architectures available, such as resnext.
