### ISSUE TITLE
How to upload image file to server for detect?

### ISSUE THREAD

**Issue by wjhtinger** [jolibrain/deepdetect#548]
I have image file on client PC, and how to use curl to upload image file to server for detect? Is there any example?

**Comment by beniz** [comment]
Hi, have you tried https://www.deepdetect.com/tutorials/object-detector/ ? It should be very easy. If you are running Docker and using files on local disks, make sure you are mounting the volumes. Happy hacking!

**Comment by wjhtinger** [comment]
beniz,
I have tried the example you said, but it use the image from url, just like: https://photos.wi.gcs.trstatic.net/e9hyHkaRFZdDV_jLZuTS6jcYq1eLUfiFzfl9zNavmNuoyZ-3UCX_EGg6D5TNU--V-f-z2CT8Kg0u3mF9gccUiA
My question is that my image is on my PC, not on the server that run deepdetect or other server can be reach by url. So how to make the deepdetect reach my image?

**Comment by beniz** [comment]
> my image is on my PC, not on the server that run deepdetect or other server can be reach by url

You either need to make your files available through a remote filesystem, or pass their content in base64 format to DD.

Note that the Python client from https://github.com/jolibrain/deepdetect/blob/master/clients/python/dd_client.py can deal with the base64 encoding for you, use the `use_base64` boolean flag.

**Comment by wjhtinger** [comment]
> 
> 
> > my image is on my PC, not on the server that run deepdetect or other server can be reach by url
> 
> You either need to make your files available through a remote filesystem, or pass their content in base64 format to DD.
> 
> Note that the Python client from https://github.com/jolibrain/deepdetect/blob/master/clients/python/dd_client.py can deal with the base64 encoding for you, use the `use_base64` boolean flag.

How to implement this by curl？Can you give a example? thanks.

**Comment by beniz** [comment]
> How to implement this by curl？Can you give a example? thanks.

I don't think `curl` can do the base64 conversion for you, so you need an external piece of code, such as the Python or other client.
