### ISSUE TITLE
Allow configuration of NCNN output blobs via API

### ISSUE THREAD

**Issue by beniz** [jolibrain/deepdetect#587]
For now, blob names are hardcoded. For `caffe2` and `tensorflow` backends we use `inputlayer` and `outputlayer` in `mllib` object, we should do the same for NCNN.

**Comment by fantes** [comment]
almost implemented. one remark : in ncnn (and tensort) the string passed is the name of the blob, not the name of the layer, while the name of the option are 'inputlayer' and 'outputlayer'
two solutions here:
- either we use the string passed as a blob name, which may be confusing as the option says 'outputlayer'  
- we internally search for blob name given layer name, which needs an update of our custom ncnn (either on ncnn itself or on the caffe2ncnn converter)

**Comment by fantes** [comment]
implemeted as a new  outputblob  param:
see  https://github.com/jolibrain/deepdetect/pull/588
