### ISSUE TITLE
How to setup an image classifier with user own trained Caffe model?

### ISSUE THREAD

**Issue by panovr** [jolibrain/deepdetect#590]
Hi,
  there are already documents explain how to setup an image classifier with pre-trained Caffe model. Can you add some documents to explain how  to setup an image classifier with user own trained Caffe model?

  For example, I have trained a model with BVLC caffe, and now I have `foo.caffemodel`, and `foo.prototxt` and `foo_solver.prototxt`.

  Thanks!

**Comment by beniz** [comment]
Hi, simply modify the inputs and outputs of your `prototxt` deploy file. The custom caffe version used by DD has many more options that's the standard one, and we recommend training the models with DD directly.
