### ISSUE TITLE
your project is very good,but can you compile the dll file and the .so file?

### ISSUE THREAD

**Issue by mengpengfei** [jolibrain/deepdetect#591]
your project is very good,but can you compile the dll file and the .so file?

so i can call the predict function with java, it is very exited

**Comment by fantes** [comment]
Hi
there has been some (unreleased) effort to compile (parts of) deepdetect for windows. Could you be more specific about your needs ? thanks

**Comment by mengpengfei** [comment]
thanks for your so fast anwer, when i see your project,i am very exited

i code in java.
i want to call the os lib file (such as xxx.dll or xxx.so)  function to predict with the trained model

**Comment by mengpengfei** [comment]
why i want to do that? because i dont want to start DeepDetect server

**Comment by beniz** [comment]
The easiest route is to start the DD server and use something like the Java client to make API calls, see https://github.com/jolibrain/deepdetect-api-java though it's a bit old now.

**Comment by mengpengfei** [comment]
thank you

is the crnn net more good than resnet+blstm+ctc?

what is the accuracy and the perfmance

**Comment by beniz** [comment]
> is the crnn net more good than resnet+blstm+ctc?

We don't use blstm for now in our applications as we found out that stacked LSTM exhibit the proper behavior. Theoretically actually, we're not sure why blstm should work better.

What we found useful is to add a third LSTM layer to the crnn and/or resnet-crnn model in some cases. It's on our task list to add these templates but you can make the modification easily yourself as well.

**Comment by mengpengfei** [comment]
how fast your test on SqueezeNet-SSD with cpu

**Comment by mengpengfei** [comment]
how much second it will consume if i predict a picture with SqueezeNet-SSD  on cpu

**Comment by mengpengfei** [comment]
when i use it to predict , do it support multi cpu?

**Comment by beniz** [comment]
Please see https://github.com/jolibrain/dd_performances. Multi-CPU is always on.
