### ISSUE TITLE
is the SqueezeNet-SSD  faster than yolov3-tiny

### ISSUE THREAD

**Issue by mengpengfei** [jolibrain/deepdetect#592]
is the SqueezeNet-SSD  faster than yolov3-tiny

**Comment by beniz** [comment]
Hi, we're not familiar with yolov3-tiny, however, the number of FLOPS reported by https://pjreddie.com/darknet/yolo/ for yolov3-tiny is 5.5Bn, while we do measure Squeezenet-SSD FLOPS to 1.2Bn, so I'd say SqueezeNet-SSD is roughly 4.5x faster than yolov3-tiny. This is from spec, not from comparing inference time.

More information is available on https://github.com/jolibrain/dd_performances

**Comment by mengpengfei** [comment]
thanks very much
