### ISSUE TITLE
does it have use openblas to get better performance on CPU ?

### ISSUE THREAD

**Issue by mengpengfei** [jolibrain/deepdetect#595]
does it have use openblas to get better performance on cpu? 

what is the min memory if i train a model on gpu  with the SqueezeNet-SSD or resnet18-ocr network

**Comment by beniz** [comment]
Hi, OpenBlas for Caffe on CPU is the default, see https://github.com/jolibrain/caffe/blob/master/Makefile.config.cpu#L40

On CPU you may want to try the NCNN backend for embedded devices, especially ARM.

Parameters (i.e. memory) and flops for a model are reported by the DD server at service creation, typically:

- CRNN (3xLSTM) Resnet-18: `[ocr_resnet_18] [info] Net total flops=678754048 / total params=12060608`

- SqueezeNet-SSD: `[squeezenet_ssd_voc] [info] Net total flops=1175515328 / total params=5409984`

**Comment by mengpengfei** [comment]
have you test the performance on cpu with the SqueezeNet-SSD network,,  i want to train on gpu,deploy on cpu, can you give me the test result,thank you
