### ISSUE TITLE
have you optimize the tcp max link limit in the deploy server container?

### ISSUE THREAD

**Issue by mengpengfei** [jolibrain/deepdetect#600]
have you optimize the tcp max link limit in the deploy server container?

the default max-limit of  linux is 1024,  if i have set the max-limit to 1000000 on  pysical computer ,

will the docker container extends the configure?

**Comment by beniz** [comment]
Hi, this is a Linux configuration thing. Maybe you need to use `ulimit` from within a custom docker build. The docker build files are available from https://github.com/jolibrain/deepdetect/tree/master/docker for you to change as needed.

**Comment by mengpengfei** [comment]
do somewhere have the install script, so i can install the deloy server on my physical computer

**Comment by beniz** [comment]
Please use the chat https://gitter.im/beniz/deepdetect
