### ISSUE TITLE
TensorRT handling mean

### ISSUE THREAD

**Issue by cchadowitz-pf** [jolibrain/deepdetect#607]
I asked this on gitter but don't want to lose track of it - if this isn't appropriate for an issue though, feel free to close it.

I'm experimenting with the new TensorRT backend and was curious how Caffe models, once converted, handle mean subtraction if the mean is originally provided via DeepDetect parameters (and isn't "baked" into the Caffe prototxt. For example, if I had this block during a Caffe service creation:
```
"parameters":{
    "input":{
      "connector":"image",
      "width":224,
      "height":224,
      "mean":[104, 117, 123]
    },
...
```
and then convert that to TensorRT, will the `mean` values still be honored?

**Comment by fantes** [comment]
Hi

in that case, the mean values should be honored, but I have not tested it explicitly. Please let us know if you have any trouble with them.

**Comment by beniz** [comment]
From what I see in the code, the mean seems correctly handled, closing for now.
