### ISSUE TITLE
Infinite prediction call (prediction stuck because of data retrieval)

### ISSUE THREAD

**Issue by YaYaB** [jolibrain/deepdetect#647]
#### Configuration
- Version of DeepDetect:
    - Locally compiled on Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
    - Branch `Master`, 3d65432ecba9f766527aa058c15c6ac199ae9d2a
- GPUS:
    - 1 x Nvidia GTX Titan X (Maxwell)

#### Your question / the problem you're facing:
I have an issue when I want to make a prediction on an image when this image is too heavy or when it is very slow to retrieve.

#### Error message (if any) / steps to reproduce the problem:
- Launch Dede

Api call
```
./dede --port 8080
```
Serveur log output
```
DeepDetect [ commit 3d65432ecba9f766527aa058c15c6ac199ae9d2a ]
[2019-10-08 15:21:36.337] [api] [info] Running DeepDetect HTTP server on localhost:8080
```

- Launch netcat to simulate and image that can not be retrieved.
```
nc -l -p 8888 
```

- Create service

Api call
```
curl -X PUT "http://localhost:8080/services/imageserv" -d '{
      "mllib":"caffe",
      "description":"image classification service",
      "type":"supervised",
      "parameters":{
        "input":{
          "connector":"image",
          "width":224,
          "height":224
        },
        "mllib":{
          "nclasses":101
        }
      },
      "model":{
        "repository":"TODO/classification_model"
      }
    }'
```
Serveur log output
```
{"status":{"code":201,"msg":"Created"}}
```
- Create Prediction

Api call
```
curl -X POST "http://localhost:8080/predict" -d '{
      "service":"imageserv",
      "parameters":{
        "input":{
          "width":224,
          "height":224
        },
        "output":{
          "best":3
        }
      },
      "data":["http://127.0.0.1:8888"]
    }'
```

Serveur log output:
```
It's empty, nothing happens because it is still trying to download the image
```

The issue comes from the fact that no timeout is indicated for the retrieve of the data.
After checking a bit the code I found here https://github.com/jolibrain/deepdetect/blob/20c143f27a110f8fff849347dc2b42b9add92df4/src/imginputfileconn.h#L487 that we try to read the element from the **uri**.
That lead us to https://github.com/jolibrain/deepdetect/blob/9978230e916a9e30a0be4efe2c6678f7139601d9/src/inputconnectorstrategy.h#L61 where we see that we do an **http call** to retrieve the data.
Then here https://github.com/jolibrain/deepdetect/blob/9978230e916a9e30a0be4efe2c6678f7139601d9/src/utils/httpclient.hpp#L36 we see that no timeout is indicated.
Moreover the default timeout is 0 and it means that it never times out (https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html)

I've modified this behavior by setting a timeout of 10s for testing and it resolved my issue.
I set the timeout between L49 and L50 of https://github.com/jolibrain/deepdetect/blob/9978230e916a9e30a0be4efe2c6678f7139601d9/src/utils/httpclient.hpp by inserting the following:
```
request.setOpt(cURLpp::Options::Timeout(10)); 
```
The server log output is then:
```
{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error: Operation timed out after 10000 milliseconds with 0 bytes received"}}
```

It would be nice to be able to set this timeout as a parameter in the service creation request.

**Comment by beniz** [comment]
Thanks. Curl has a default 300 seconds timeout (5 mins) on connect phase (see https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html) but no default timeout on the transfer phase. PR #650 adds configurable timeout on the transfer phase, at two granularities: service creation and sample prediction.

**Comment by YaYaB** [comment]
Thanks @beniz for the quick fix.
It works very well on my side. I've tested in:
- the service creation alone;
- the predict request alone;
- the predict and the creation requests and the value in the predict call overrides well the value indicated in the creation request.

**Comment by YaYaB** [comment]
However I saw two cases we must be careful for:
- The prediction value is overridden only for this prediction. The default value set in the service creation is kept and used if no timeout is indicated in the prediction call;
- If no value is indicated in the creation service, the prediction's value is used. However the default value still remains as None. If prediction A has a timeout of 5 and prediction B has no timeout then prediction B will be infinite
