### ISSUE TITLE
RefineDet fails with `nclasses`=3

### ISSUE THREAD

**Issue by beniz** [jolibrain/deepdetect#654]
Issue: `refinedet_512` caffe template fails when `nclasses`=3. I can't find the source of the issue in the parameter automatic scaling in `caffelib.cc`. I guess it thus might be in Caffe itself.

Workaround: use `nclasses`=4 and ignore class number 3.

**Comment by beniz** [comment]
Same behavior observed for `nclasses=5`.

**Comment by fantes** [comment]
issue come from come cudnn curse. workaround is to set  params.mllib.engine either to: CUDNN_SINGLE_HANDLE CUDNN_MIN_MEMORY of CAFFE (no cudnn)   

[ CUDNN fails, and so does DEFAULT, which is same as CUDNN when caffe is compiled with cudnn ]
