### ISSUE TITLE
in detection models (ssd), in predict output :  ymin and ymax are swapped 

### ISSUE THREAD

**Issue by fantes** [jolibrain/deepdetect#674]
ie ymax < ymin , 

- change in dd to do here : https://github.com/jolibrain/deepdetect/blob/master/src/backends/caffe/caffelib.cc#L2560  (replace ymax by ymin and reverse) , reference in caffe :  https://github.com/jolibrain/caffe/blob/master/src/caffe/util/bbox_util.cpp#L2105  (same in cuda) 

- change in platform to do here (ymin - ymax)
https://github.com/alx/react-bounding-box/blob/master/src/react-bounding-box.js#L394

**Comment by YaYaB** [comment]
Please make a release when this is pushed to master as it has a big impact for those using detection models.

**Comment by fantes** [comment]
https://github.com/jolibrain/deepdetect/pull/690

**Comment by alx** [comment]
Fixed in `react-bounding-box` v0.5.3: https://www.npmjs.com/package/react-bounding-box/v/0.5.3

**Comment by fantes** [comment]
> Fixed in `react-bounding-box` v0.5.3: https://www.npmjs.com/package/react-bounding-box/v/0.5.3

:+1:
