### ISSUE TITLE
Load caffe models into deepdetect 

### ISSUE THREAD

**Issue by lucmichalski** [jolibrain/deepdetect#727]
Hi,

What is the process in order to load these models into deepdetect ?

Refs:
- https://github.com/eric612/TensorRT-Yolov3-models
- https://github.com/eric612/MobilenetV3-Caffe

Thanks

**Comment by beniz** [comment]
>     * https://github.com/eric612/MobilenetV3-Caffe

This should work if you apply the following steps:
- Change `DepthwiseConvolution` in the prototxt file with `ConvolutionDepthwise`
- Rename the `MobileNetV3.prototxt` into `deploy.prototxt`
- Change the first layer as described in the FAQ's "How to import a model from Caffe into DeepDetect" section, i.e. your `deploy.prototxt` file should begin with:
```
name: "MobileNetV3"
input: "blob1"
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 32
    channels: 3
    height: 224
    width: 224
  }
  include {
    phase: TEST
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 16
    bias_term: false
    pad: 1
    kernel_size: 3
    group: 1
    stride: 2
    weight_filler {
      type: "xavier"
    }
    dilation: 1
  }
}
```
Put the `deploy.prototxt` and the `.caffemodel` files into a directory. You should then be able use the API to create a service for this model.
