### ISSUE TITLE
Core dump with svm and db true

### ISSUE THREAD

**Issue by YaYaB** [jolibrain/deepdetect#742]
- Version of DeepDetect:
    - [X] Locally compiled on:
        - [X] Ubuntu 14.04 LTS
        - [ ] Mac OSX
        - [ ] Other:
    - [ ] Docker
    - [ ] Amazon AMI
- Commit (shown by the server when starting):
c6d27f8d69336b89eb1467e44ffe1d2cd350bd87
#### Your question / the problem you're facing:
I have trained a model with the svm connector. I obtain a core dump if I run a prediction on a svm file while keeping the **db: true** in the service creation. I know this is not the best practice however the core dump is not appreciated ^^

I joined a random model.
To replicate you can just download it and extract it.
In the next section we will consider **PATH_MODEL** as the path where the model is stored

#### Error message (if any) / steps to reproduce the problem:
We launch th service with  "db":false.
- [ ] list of API calls:
```
    curl -X PUT "http://localhost:8082/services/svm_test" -d '{
        "mllib":"caffe",
        "description":"image classification service",
        "type":"supervised",
        "parameters":{
            "input":{
            "connector":"svm"
            },
            "mllib":{
                "db": false,
                "nclasses":2
            }
        },
        "model":{
            "repository":"PATH_MODEL"
        }
  }'
```
    

- [ ] Server log output:
```
[2020-06-24 08:14:04.449] [svm_test] [info] Using pre-trained weights from PATH_MODEL/model_iter_0.caffemodel
[2020-06-24 08:14:04.459] [caffe] [info] Ignoring source layer drop_ip0
[2020-06-24 08:14:04.460] [caffe] [info] Ignoring source layer drop_ip1
[2020-06-24 08:14:04.460] [caffe] [info] Ignoring source layer drop_ip2
[2020-06-24 08:14:04.461] [svm_test] [info] Net total flops=2626560 / total params=2626560
[2020-06-24 08:14:04.461] [svm_test] [info] detected network type is classification
[2020-06-24 08:14:04.461] [api] [info] 127.0.0.1 "PUT /services/svm_test" 201 2104
```

Then we make a prediction

- [X] list of API calls:
```
curl -X POST "http://localhost:8082/predict" -d '{
    "service":"svm_test",
    "parameters":{
        "input":{
        },
        "output":{
        "best":-1
        }
    },
    "data":["PATH_MODEL/test.svm"]
}'
```
- [X] Server log output:
```
[2020-06-24 08:16:30.271] [svm_test] [info] SVM fname=PATH_MODEL/test.svm / open=true
[2020-06-24 08:16:30.271] [svm_test] [info] total number of dimensions=2
[2020-06-24 08:16:30.271] [svm_test] [info] read 2 lines from SVM data file
[2020-06-24 08:16:30.329] [api] [info] 127.0.0.1 "POST /predict" svm_test 200 61
```
and we obtain
```
{"status":{"code":200,"msg":"OK"},"head":{"method":"/predict","service":"svm_test","time":60.0},"body":{"predictions":[{"classes":[{"prob":0.5137032270431519,"cat":"1"},{"prob":0.48629680275917055,"last":true,"cat":"0"}],"uri":"0"},{"classes":[{"prob":0.5573678016662598,"cat":"1"},{"prob":0.4426322877407074,"last":true,"cat":"0"}],"uri":"1"}]}}%  
```

Here it seems to work well. Now if we do the same thing but when we create the service we set **db: true** here is what we obtain when making the prediction
- [X] list of API calls:
```
    curl -X PUT "http://localhost:8082/services/svm_test" -d '{
        "mllib":"caffe",
        "description":"image classification service",
        "type":"supervised",
        "parameters":{
            "input":{
            "connector":"svm"
            },
            "mllib":{
                "db": false,
                "nclasses":2
            }
        },
        "model":{
            "repository":"PATH_MODEL"
        }
  }'
```

```
curl -X POST "http://localhost:8082/predict" -d '{
    "service":"svm_test",
    "parameters":{
        "input":{
        },
        "output":{
        "best":-1
        }
    },
    "data":["PATH_MODEL/test.svm"]
}'
```
- [X] Server log output:
```
[2020-06-24 08:18:26.457] [svm_test] [info] SVM fname=PATH_MODEL/test.svm / open=true
[2020-06-24 08:18:26.457] [svm_test] [info] total number of dimensions=2
[1]    1207 segmentation fault (core dumped)  ./dede --port 8082
```
and 
```
curl: (52) Empty reply from server
```

As you can see, we observe a core dump.
I tried the same thing with the image connector and it does not core dump.

Thanks in advance for your help
[bug_svm_prediction.zip](https://github.com/jolibrain/deepdetect/files/4824058/bug_svm_prediction.zip)
[bug_svm_prediction.zip](https://github.com/jolibrain/deepdetect/files/4824060/bug_svm_prediction.zip)

**Comment by fantes** [comment]
this should be fixed in  : 
https://github.com/jolibrain/deepdetect/pull/744

a lot of thanks for the perfect bug reports, it saved a lot of time !

**Comment by YaYaB** [comment]
Your fix works like a charm for me!

**Comment by fantes** [comment]
yup, there definitely is some black magic at work here  :)

**Comment by dgtlmoon** [comment]
Is https://github.com/jolibrain/deepdetect/pull/586 related?
