### ISSUE TITLE
Docs missing db:true please fix!

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#750]
https://www.deepdetect.com/server/docs/train-image-classifier/

https://github.com/jolibrain/deepdetect/issues/431#issuecomment-422286767

https://github.com/jolibrain/deepdetect/issues/748#issuecomment-651338351

please fix, lost about a full day here :/

**Comment by dgtlmoon** [comment]
can result in `    "dd_msg": "vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)"` if `db:true` is missing aswell

**Comment by beniz** [comment]
Thanks for the feedback, this should be fixed now!

**Comment by dgtlmoon** [comment]
fantastic!!! :)
