### ISSUE TITLE
Following the train-image-classifier docs gives error "Service Input Error: no image data found in repository"

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#751]
#### Configuration
- Version of DeepDetect:
    - [ ] Locally compiled on:
        - [ ] Ubuntu 14.04 LTS
        - [ ] Mac OSX
        - [ ] Other:
    - [ x] Docker
    - [ ] Amazon AMI
- Commit (shown by the server when starting):

#### Your question / the problem you're facing:

I'm following https://www.deepdetect.com/server/docs/train-image-classifier/ as close as possible, and taking into account that `db:true` was missing according to #750 , I get ` "dd_msg": "Service Input Error: no image data found in repository"`

I've tried docker CPU and GPU, same result.

The data is available from INSIDE the container at the path it expects.
```
dd@4d42447d41ef:/opt/deepdetect/build/main$ ls -al /opt/models/cats_dogs/train/|wc -l
25003
```
```
dd@b9bdab4f726c:/opt/deepdetect/build/main$ ls -al /opt/models/cats_dogs/train/|head -n10
total 609256
drwxr-xr-x 2 root root 765952 Sep 20  2013 .
drwxrwxrwx 3 dd   dd     4096 Jun 30 15:40 ..
-rw-r--r-- 1 root root  12414 Sep 20  2013 cat.0.jpg
-rw-r--r-- 1 root root  16880 Sep 20  2013 cat.1.jpg
-rw-r--r-- 1 root root  34315 Sep 20  2013 cat.10.jpg
-rw-r--r-- 1 root root  28377 Sep 20  2013 cat.100.jpg
-rw-r--r-- 1 root root   5944 Sep 20  2013 cat.1000.jpg
-rw-r--r-- 1 root root  21944 Sep 20  2013 cat.10000.jpg
-rw-r--r-- 1 root root  27322 Sep 20  2013 cat.10001.jpg
```

I see there are a good number of images
```
 ls train/|awk -F'.' '{print $1}'|sort|uniq -c
  12500 cat
  12500 dog
```

#### Error message (if any) / steps to reproduce the problem:
- [ ] list of API calls:

```
curl -X PUT "http://localhost:8080/services/catsdogs" -d '{
       "mllib":"caffe",
       "description":"image classification service",
       "type":"supervised",
       "parameters":{
         "input":{
           "connector":"image",
           "width":224,
           "height":224,
           "db": true
         },
         "mllib":{
           "nclasses":2,
           "template": "se_resnet_50",
           "finetuning":true
         }
       },
       "model":{
         "templates":"../templates/caffe/",
         "repository":"/opt/models/cats_dogs",
         "weight" : "SE-ResNet-50.caffemodel"
       }
     }'

sleep 2

curl -X POST "http://localhost:8080/train" -d '{
       "service":"catsdogs",
       "async":true,
       "parameters":{
         "input":{
           "connector":"image",
           "test_split":0.1,
           "shuffle":true,
           "width":224,
           "height":224
         },
         "mllib":{
           "gpu":true,
           "mirror":true,
           "net":{
             "batch_size":32
           },
           "solver":{
             "test_interval":500,
             "iterations":5000,
             "base_lr":0.001
           },
       "noise":{"all_effects":true, "prob":0.001},
       "distort":{"all_effects":true, "prob":0.01}
         },
         "output":{
           "measure":["acc","mcll","f1"]
         }
       },
       "data":["/opt/models/cats_dogs/train/"]
     }'
```

- [ ] Server log output:

```
{
    "status": {
        "code": 200,
        "msg": "OK"
    },
    "head": {
        "method": "/train",
        "job": 1,
        "status": "error"
    },
    "body": {
        "Error": {
            "code": 400,
            "msg": "BadRequest",
            "dd_code": 1005,
            "dd_msg": "Service Input Error: no image data found in repository"
        }
    }
}

```

Bonus: would be nice if it would print out the repository directory it expected too

**Comment by dgtlmoon** [comment]
Looking at the source, it seems that the documentation is wrong

` "data":["/opt/models/cats_dogs/train/"]` is right however it is expecting the images to exist in sub-directories under the `data[]` path

so this means something like 

```
mkdir /opt/models/cats_dogs/train/dogscatsdata
mv /opt/models/cats_dogs/train/*jpg /opt/models/cats_dogs/train/dogscatsdata
```

![image](https://user-images.githubusercontent.com/275001/86150939-5e03fa80-bafe-11ea-9359-8cdc8e7be2a2.png)

Looking at https://www.deepdetect.com/dd/datasets/cats_dogs.zip

```
Archive:  cats_dogs.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2013-09-20 10:12   train/
    12414  2013-09-20 10:05   train/cat.0.jpg
    16880  2013-09-20 10:05   train/cat.1.jpg
    34315  2013-09-20 10:05   train/cat.10.jpg
    28377  2013-09-20 10:05   train/cat.100.jpg
     5944  2013-09-20 10:05   train/cat.1000.jpg
    21944  2013-09-20 10:05   train/cat.10000.jpg
    27322  2013-09-20 10:05   train/cat.10001.jpg
    25723  2013-09-20 10:05   train/cat.10002.jpg
    28035  2013-09-20 10:05   train/cat.10003.jpg
    12973  2013-09-20 10:05   train/cat.10004.jpg
     8245  2013-09-20 10:05   train/cat.10005.jpg
```


![image](https://user-images.githubusercontent.com/275001/86150759-1bdab900-bafe-11ea-9ab5-02b24221c68d.png)

again, documentation issue i think

**Comment by dgtlmoon** [comment]
Can I edit the documentation somehow? Is it possible to make a merge request? i've lost nearly 2 full days to this and similar minor documentation issue

**Comment by dgtlmoon** [comment]
Is the leading slash in `"data":["/opt/models/cats_dogs/train/"] ` a problem? need to check

**Comment by beniz** [comment]
you need 
```
cat_dog/train/dogs
cat_dog/train/cats
```
And this should work fine. You can look here also that lists a typical directory for training an image classifier, https://www.deepdetect.com/platform/docs/image-classification/

Let us know if it doesn't. The documentation is on git but not public since it contains the whole website as well. We shall find a way to open it up in the future.

**Comment by dgtlmoon** [comment]
@beniz I've lost days to reading wrong documentation and blaming myself, problem is that https://www.deepdetect.com/server/docs/train-image-classifier/ does not explain that it needs to be in `cat_dog/train/dogs/` format, because 

- its too hard to update the documentation
- too hard for other people to update the documentation (public stuff not part of the git repo, cant pull request)
- documentation maybe out of date
- how am I meant to know that https://www.deepdetect.com/server/docs/train-image-classifier/ is wrong compared to https://www.deepdetect.com/platform/docs/image-classification/ ?

etc
etc

**Comment by dgtlmoon** [comment]
It must be hard/extra work on you having to answer all these small questions about why things dont work, when the docs aren't quite 100% :/

**Comment by beniz** [comment]
Your frustration is understandable, and your feedback is appreciated and well recorded. It's pretty common that code moves faster than documentation. Our staff is most of the time due elsewhere with our customers, but the team is due to grow soon and thus things should get more polished over time. When there's a will, there's a way isn't it ?

In all cases with (free) Open Source, looking at the code often yields the final answer and teaches the low level details.

Closing this for now, hope your application is moving forward!
