### ISSUE TITLE
DDPlatform: unable to access Predict services

### ISSUE THREAD

**Issue by vd3d** [jolibrain/deepdetect#766]
Hi,

I have installed the DD platform, and when I click on the "Predict services" I got a white page.
I've checked into the JS console and see some issues:

![image](https://user-images.githubusercontent.com/17200971/89266547-558b6c00-d636-11ea-957d-d8db314eefa4.png)

Does anyone have an idea of the issue?

It seems I have a lot of 404 issues...

I also see such attempts to access, but my version is CPU only
http://localhost:1912/gpu/stats 

#### Configuration
Docker swarm
Windows 10
CPU only

**Comment by vd3d** [comment]
Hi,

Is it possible to have some help please? I can't find a way to make it work and searching since 2 weeks now :-(

I use the CPU version because my GPUs are AMD one !

**Comment by beniz** [comment]
Hi, can you use `docker ps` to see what components of  the platform are running on your machine ?

**Comment by vd3d** [comment]
Hi Beniz,

Here it is:

CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                          PORTS                    NAMES
87b3a927f1e1        jolibrain/ouroboros               "ouroboros"              43 hours ago        Up 24 hours
                             gpu_ouroboros_1
38a19f838ad4        jolibrain/platform_ui:latest      "nginx -g 'daemon of…"   43 hours ago        Up 24 hours
    80/tcp                   gpu_platform_ui_1
2cb8fee9b47c        amir20/dozzle                     "/dozzle"                43 hours ago        Up 24 hours
    8080/tcp                 gpu_dozzle_1
59cd5e900b7d        nginx:latest                      "/docker-entrypoint.…"   11 days ago         Restarting (1) 51 seconds ago                            cpu_nginx_1
4b6455d984bd        jolibrain/deepdetect_cpu          "/bin/sh -c './dede …"   4 weeks ago         Up 24 hours
    0.0.0.0:8080->8080/tcp   cpu_deepdetect_1
4541b1c3ae09        filebrowser/filebrowser:v1.10.0   "/filebrowser --conf…"   4 weeks ago         Up 24 hours
    80/tcp                   cpu_filebrowser_1
2a93dc9ca63c        jolibrain/platform_ui:latest      "nginx -g 'daemon of…"   4 weeks ago         Up 24 hours
    80/tcp                   cpu_platform_ui_1
ac7fc9631901        amir20/dozzle                     "/dozzle"                4 weeks ago         Up 24 hours
    8080/tcp                 cpu_dozzle_1

**Comment by beniz** [comment]
The one restarting is not from the DD platform I believe. Did you customize the standard installation ?

**Comment by vd3d** [comment]
I'm under Windows 10, so there is no CURRENT_UID, neither MUID.

So, I had to remove all the references to them in the docker compose file. I join it.
[docker-compose.zip](https://github.com/jolibrain/deepdetect/files/5078649/docker-compose.zip)

But, nginx does not have any reference to them btw.

Maybe it will be great to have also the .bat or .ps1 files for windows.
PS: if we fix it, I can provide mine.

**Comment by beniz** [comment]
Unfortunately at this stage we can't offer support on Windows. Though we've had feedback that it seems to work. Have you tried installing a simple CPU DD server docker image and playing with it ? The 404 error seems to originate from a predict call that can't reach the CPU DD server docker.

**Comment by vd3d** [comment]
There is no windows version, it is why I try to make mine!

The simple DD server work fine. But not the platform under Windows+CPU!

First, I have try to run the docker compose, as is, but it does not work!

It looks that it try to reach the "gpu" (and not cpu) server ... see "gpu/stats" ... or maybe it is just the name!
But definitively, it does not work on windows... I try to make it work since weeks now :-(

Any idea ?

**Comment by dgtlmoon** [comment]
@vd3d they don't really officially support windows from what I've read... so I'm not sure how you can expect them to solve the problems... in any case windows UID and Linux UID stuff would be very very different..

I would recommend just firing up a GPU over at paperspace.com , that's what I do, works great, nice price too :)

**Comment by alx** [comment]
Hi @vd3d 

Thanks for your feedback, I've had a look at the code, specially around the undefined `recommendedGpuIndex` and pushed a new docker image tagged `dev`. Could you use this image and tell me if you can access the 'Predict services' page ? You'll need to edit your `docker-compose.yml` file and setup `platform_ui` container image as followed:

```
  platform_ui:
    ...
    image: jolibrain/platform_ui:dev
    ...
```

If you have access to other pages, it's probably not an `nginx` issue. All other 404 errors are related to services not running within your `docker-compose` setup (like gpu monitoring).

I'm looking to know if it solved your issue, feel free to contact me if you need more information.

Alex

**Comment by simogogo** [comment]
Hi,
I registered the same issue on a Ubuntu 16.04 in a docker deployment...
For me the "dev" version of platform_UI solved the issue

**Comment by alx** [comment]
Hi @simogogo 

Thanks for the feedback, we were able to reproduce this error on `latest` and `v0.9.7.2` container image for `platform_ui`.

`latest` image and `v0.9.7.3` container image is now available with a fix for this issue: https://hub.docker.com/r/jolibrain/platform_ui

**Comment by alx** [comment]
I'm closing this issue, feel free to re-open it if this behavior persists on latest docker images.
