### ISSUE TITLE
Documentation bug: model weights in object detection documentation do not exist

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#773]
https://www.deepdetect.com/platform/docs/object-detection/

![image](https://user-images.githubusercontent.com/275001/90443116-fe78a300-e0db-11ea-8bda-9352ee7c53e4.png)

```
dd@a0a6e47be381:/opt/deepdetect/build/main$ ls -al /opt/platform/models/pretrained
ls: cannot access '/opt/platform/models/pretrained': No such file or directory
```

In the latest GPU docker image, I have only

```
dd@a0a6e47be381:/opt/deepdetect/build/main$ find /opt|grep caffemodel
/opt/models/resnet_50/ResNet-50-model.caffemodel
/opt/models/ggnet/bvlc_googlenet.caffemodel
```

**Comment by dgtlmoon** [comment]
![image](https://user-images.githubusercontent.com/275001/90447929-ad20e180-e0e4-11ea-9a2d-9a73a14ec2e5.png)

```
dd@d8bfd627e7fd:/opt/deepdetect/build/main$ find /opt|grep caffemod
/opt/models/resnet_50/ResNet-50-model.caffemodel
/opt/models/ggnet/bvlc_googlenet.caffemodel
```

**Comment by dgtlmoon** [comment]
I checked the docker images for `cpu platform docker`, `gpu` and `cpu` and not in those either

**Comment by beniz** [comment]
Hi, yes it's a known issue on some installs. The tarball is available from https://www.deepdetect.com/downloads/platform/pretrained_latest.tar.gz

**Comment by dgtlmoon** [comment]
Got another one, the headers on the table are the wrong way around..

![image](https://user-images.githubusercontent.com/275001/90497570-821ba980-e147-11ea-87b2-d0770cadf8fa.png)

**Comment by dgtlmoon** [comment]
Could be nice to add the following comments (as an example)

**Image size** - deep detect will resize the image automatically, but this is the internal image size used in the network layer structure.

**template** - used in the  `"mllib":{  "template":` field, this is required, if we were not finetuning (`finetuning` not set or is `false`) then we can just use this template to train new weights on, otherwise you need to provide the `template` and the current pretrained `weights`, which should be for the same model.

**Comment by dgtlmoon** [comment]
@alx easy solution would be, under the table of models, just include a link "Download the pretrained weights file for the model here https://www.deepdetect.com/downloads/platform/pretrained/"

**Comment by alx** [comment]
Hi @dgtlmoon 

Thanks again for your feedbacks, I've updated the documentation page using them: https://www.deepdetect.com/platform/docs/object-detection/

I'm not sure where to insert your comment about the **template** parameter, you provide a curl parameter while this page is showing an example of a jupyter notebook snippet.

**Comment by alx** [comment]
Documentation has been updated and published, feel free to re-open this issue to append new comments about this section.

We're planning to move the documentation on github, you should soon be able to make PR on it.

Have a nice day,

Alex
