### ISSUE TITLE
Documentation bug: Squeezenet model is findable on google, but does not exist on the models page

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#774]
https://www.deepdetect.com/models/squeezenet/

But does not exist here

https://www.deepdetect.com/models/?opts={%22media%22:%22image%22,%22type%22:%22type-all%22,%22backend%22:[%22caffe%22,%22caffe2%22,%22tensorflow%22,%22ncnn%22],%22platform%22:%22desktop%22,%22searchTerm%22:%22%22}#

![image](https://user-images.githubusercontent.com/275001/90446830-5b775780-e0e2-11ea-8d9b-a2ae1f3e378e.png)

**Comment by alx** [comment]
Hi @dgtlmoon 

Thanks for the feedback.

Squeezenet model is available on the model listing page when "Embedded" button is selected.

![image](https://user-images.githubusercontent.com/373/90483722-6dceb100-e135-11ea-9125-4744aa6767d7.png)
