### ISSUE TITLE
Minor documentation helper: Object class 0 is always the background class, and thus user object classes start with number 1. 

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#793]
A little timesaver.. 

At https://www.deepdetect.com/platform/docs/object-detection/ `Object class 0 is always the background class, and thus user object classes start with number 1. `

Would be nice to add that "If you receive `exception while forward/backward pass through the network`  and it's not due to memory or other problems, check that the number `n_classes` is your expected number of classes plus 1"

In my case, I got this error because I was training on 4 classes, but my `n_classes` was 4, not 5.

:)

**Comment by alx** [comment]
Hi @dgtlmoon ,

Thanks for the tips, the platform documentation has been updated.

Have a nice day,

Alex
