### ISSUE TITLE
Add "non-backwards compatible" section to release notes

### ISSUE THREAD

**Issue by cchadowitz-pf** [jolibrain/deepdetect#862]
It would be great if new releases had a section for "non-backwards compatible" or "breaking changes" that breaks or fundamentally changes functionality from the previous version - thanks in advance!

**Comment by sileht** [comment]
We automated the changelogs generation and follow https://www.conventionalcommits.org/en/v1.0.0/ now.

Any commit with `BREAKING CHANGE:` will bump the major release and add a dedicated section inside the release note and changelog.
