### ISSUE TITLE
Image classifier setup docs link to localhost for downloading other provided models from DD

### ISSUE THREAD

**Issue by dgtlmoon** [jolibrain/deepdetect#874]
https://www.deepdetect.com/server/docs/imagenet-classifier/

"Let us use a pre-trained model with the Googlenet architecture. However, this tutorial can be reproduced by using any of the other image classification models we provide."

![image](https://user-images.githubusercontent.com/275001/95665148-d478b580-0b4d-11eb-9d4b-aec3b8273151.png)

**Comment by alx** [comment]
Fixed on https://www.deepdetect.com/server/docs/imagenet-classifier/
