### ISSUE TITLE
Pytorch Jupyter Cuda Support

### ISSUE THREAD

**Issue by tlok666** [jolibrain/deepdetect#997]
#### Configuration

- Version of DeepDetect: v0.11.0
    - [ ] Locally compiled on:
        - [ ] Ubuntu 20.04 LTS
    - [ ] Docker GPU 2 TITAN Xp

#### Your question / the problem you're facing:
I have tried jolibrain/deepdetect_gpu_torch:latest and  jolibrain/deepdetect_gpu_torch:v0.11.0
but none of them works on pytorch cuda
How could I make it work?
![image](https://user-images.githubusercontent.com/12291907/99891686-a12a5a00-2ca7-11eb-9536-cf7adce946ea.png)

**Comment by sileht** [comment]
Hi, the docker images of deepdetect provide a REST API on top of different machine learning libraries, they are not jupyter distributions.

When you do 
```
import torch
torch.cuda.is_available()
```
There is no involvement of deepdetect here, you are just loading the pytorch version shipped with your Jupyter.

I'm not sure about what you trying to achieve. Did you install the complete deepdetect platform ? Or is it your own installation of Jupyter?

**Comment by tlok666** [comment]
> Hi, the docker images of deepdetect provide a REST API on top of different machine learning libraries, they are not jupyter distributions.
> 
> When you do
> 
> ```
> import torch
> torch.cuda.is_available()
> ```
> 
> There is no involvement of deepdetect here, you are just loading the pytorch version shipped with your Jupyter.
> 
> I'm not sure about what you trying to achieve. Did you install the complete deepdetect platform ? Or is it your own installation of Jupyter?

**Comment by tlok666** [comment]
I installed the complete deepdetect platform. The docker was installed under the guidance below.
![image](https://user-images.githubusercontent.com/12291907/99946736-d4591000-2db1-11eb-8c60-6a5282b99c94.png)

And the Jupyter was started from the deepdetect website.  127.0.0.1:1912

Do you mean the pytorch version shipped with the docker of  _jolibrain/jupyter_dd_notebook_ ?


> Hi, the docker images of deepdetect provide a REST API on top of different machine learning libraries, they are not jupyter distributions.
> 
> When you do
> 
> ```
> import torch
> torch.cuda.is_available()
> ```
> 
> There is no involvement of deepdetect here, you are just loading the pytorch version shipped with your Jupyter.
> 
> I'm not sure about what you trying to achieve. Did you install the complete deepdetect platform ? Or is it your own installation of Jupyter?

**Comment by tlok666** [comment]
I am a new starter of deepdetect, I was trying to use the complete dd_platform to train and forward PyTorch models. So, I installed the complete dd_platform and start the JupyterLab from the website. 

When I use the 'torch.cuda.is_available()' in the JupyterLab, I found it is not supported.

Besides, in the Predict page. The Pytorch mllib is still not supported yet?

**Comment by sileht** [comment]
The user of our platform does their machine learning works with deepdetect, and not directly with the underlying ml lib.
That why this doesn't work out of the box.

I opened a PR to add access from Jupyter to the GPUs here https://github.com/jolibrain/dd_platform_docker/pull/45.
It can be useful for debugging, but nothing more.

**Comment by tlok666** [comment]
Thanks.  [ jolibrain/dd_platform_docker#45](url).   solves my question.

For the ml lib, I think this is another question. How to use Pytorch in the 'Predict services'.
